name: Build iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install briefcase

    - name: Build iOS app
      run: |
        source venv/bin/activate
        briefcase package iOS
        briefcase open iOS

    - name: Create ExportOptions.plist
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>FW524XZH8Z</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
        </dict>
        </plist>' > ExportOptions.plist
      
    - name: Xcode Package app
      run: |
        xcodebuild -project "build/simpleapp/ios/xcode/simple app.xcodeproj" -scheme "simple app" -destination 'generic/platform=iOS' -configuration Release clean build
        xcodebuild -project "build/simpleapp/ios/xcode/simple app.xcodeproj" -scheme "simple app" -archivePath "./build/simple app.xcarchive" archive
        xcodebuild -exportArchive -archivePath "./build/simple app.xcarchive" -exportPath ./build/ -exportOptionsPlist ExportOptions.plist

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "shivank chhaya"
        git config --global user.email "shivank.chhaya@gmail.com"
        git add .
        git reset -- venv
        git commit -m "added distribution"
        git push origin main